services:
  - type: web
    name: contexthub-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm run start
    envVars: []

  - type: static
    name: contexthub-frontend
    env: static
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
